name: Feature Request
description: Suggest an idea for the COBOL Programming Course
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a feature request. Please fill in the information below and we will get back to you as soon as possible.
  
        Before opening a feature request, please search our existing issues: https://github.com/openmainframeproject/cobol-programming-course/issues. 
  - type: dropdown
    attributes:
      label: Course Details
      description: Where did you take the course?
      options:
        - GitHub
        - IBM Learning Platform
        - Coursera
        - edX
        - Pluralsight
        - YouTube
    validations:
      required: true
  - type: textarea
    attributes:
      label: Description
      description: Describe what you want to happen. 
    validations:
      required: true
  - type: textarea
    attributes:
      label: Problems
      description: Is your feature request related to a problem? Please describe.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: Any other context about the problem?
    validations:
      required: false
